spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        url: jdbc:mysql://192.168.0.30:3306/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true
    slave:
        url: jdbc:mysql://192.168.0.31:3306/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.jdbc.Driver
        username: readonlyuser
        password: readonlyuser
        initial-size: 5
        min-idle: 1
        max-active: 100
        test-on-borrow: true

mybatis:
  mapper-locations: classpath:com/ding/readWriteSparation/mapping/*.xml
  type-aliases-package: com.ding.readWriteSparation.model.entity

